### ISSUE TITLE
Add ProjectionExpression in the queries

### ISSUE THREAD

**Issue by 01123899** [rh389/dynamodb-geo.js#20]
How can i work with ProjectionExpression?
I try with ProjectionExpression: "nameAttribute1,nameAttribute2"
but it gives me this error -> TypeError: Cannot read property 'S' of undefined

**Comment by peterWilson34** [comment]
the same issue here

**Comment by rh389** [comment]
I'm assuming you're trying something like this?

```js
myGeoTableManager.queryRadius({
        RadiusInMeter: 100000,
        CenterPoint: {
            latitude: 52.225730,
            longitude: 0.149593
        },
        QueryInput: {
            ProjectionExpression: "nameAttribute1,nameAttribute2"
        }
    })
``` 

The problem is that this won't return the `geoJson` attribute, which is needed by this lib to filter your results by radius / rectangle. You'll need to make sure `geoJson` (or whatever custom name you've given it) is part of your projection expression.

Let me know if that doesn't help and I'll reopen.
