### ISSUE TITLE
Is there a reason that original JAVA version is archived?

### ISSUE THREAD

**Issue by uronly14me** [rh389/dynamodb-geo.js#41]
I found that the original version was archived. Is there a reason for that?

https://github.com/awslabs/dynamodb-geo

**Comment by robhogan** [comment]
I've never been involved with that project. At a guess, it could be because it's no longer an optimal implementation since the arrival of newer features like GSIs. It also had at least one nasty design error in that lat/lng pairs were stored in the wrong order relative to the GeoJSON spec. The original lib dates from 2013 and always felt more like a proof of concept than a commitment - perhaps bringing it up to date was felt to be too much of an undertaking.

AWS labs projects come and go generally I guess. Hopefully at some point geo queries will be a native feature..
